2021-01-06 15:59:52,960 (25312/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 15:59:52,961 (25312/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 15:59:52,966 (25312/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-01-06 16:00:14,949 (25335/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:00:14,949 (25335/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:01:48,037 (25335/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2021-01-06 16:01:48,038 (25335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2021-01-06 16:12:25,613 (25335/MainThread) pgcli.pgexecute ERROR - sql: 'insert into postres (name) values (Alonso) (Pedro) (Julio)', error: SyntaxError('syntax error at or near "("\nLINE 1: insert into postres (name) values (Alonso) (Pedro) (Julio)\n                                                   ^\n')
2021-01-06 16:12:25,613 (25335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "("\nLINE 1: insert into postres (name) values (Alonso) (Pedro) (Julio)\n                                                   ^\n\n'
2021-01-06 16:12:52,401 (25335/MainThread) pgcli.pgexecute ERROR - sql: 'insert into postres (name) values (Alonso), (Pedro), (Julio)', error: UndefinedColumn('column "alonso" does not exist\nLINE 1: insert into postres (name) values (Alonso), (Pedro), (Julio)\n                                           ^\n')
2021-01-06 16:12:52,401 (25335/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "alonso" does not exist\nLINE 1: insert into postres (name) values (Alonso), (Pedro), (Julio)\n                                           ^\n\n'
2021-01-06 16:17:46,214 (25992/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:17:46,214 (25992/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:50:05,161 (27343/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:50:05,162 (27343/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:54:02,074 (27703/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:54:02,075 (27703/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:54:14,790 (27713/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:54:14,791 (27713/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:54:16,634 (27713/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 545?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 545?\n\n'
2021-01-06 16:54:19,603 (27731/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:54:19,604 (27731/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:54:22,027 (27731/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 545?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 545?\n\n'
2021-01-06 16:54:28,184 (27741/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:54:28,185 (27741/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:55:03,312 (27805/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:55:03,314 (27805/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 16:55:24,644 (27862/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 16:55:24,646 (27862/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-06 17:30:45,466 (29790/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-06 17:30:45,467 (29790/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-07 08:53:13,488 (2626/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-07 08:53:13,489 (2626/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-07 08:53:24,823 (2637/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-07 08:53:24,823 (2637/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-07 08:53:30,249 (2637/MainThread) pgcli.pgexecute ERROR - sql: '\\dl', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\dl\n        ^\n')
2021-01-07 08:53:30,251 (2637/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\dl\n        ^\n\n'
2021-01-07 09:11:53,983 (2637/MainThread) pgcli.pgexecute ERROR - sql: 'drop table Car', error: UndefinedTable('table "car" does not exist\n')
2021-01-07 09:11:53,990 (2637/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: table "car" does not exist\n\n'
2021-01-07 09:56:28,371 (2637/MainThread) pgcli.pgexecute ERROR - sql: 'dt', error: SyntaxError('syntax error at or near "dt"\nLINE 1: dt\n        ^\n')
2021-01-07 09:56:28,372 (2637/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "dt"\nLINE 1: dt\n        ^\n\n'
2021-01-08 09:47:26,427 (3555/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-08 09:47:26,428 (3555/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-08 10:24:13,845 (5368/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-08 10:24:13,848 (5368/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-08 10:31:30,552 (5368/MainThread) pgcli.pgexecute ERROR - sql: 'gst', error: SyntaxError('syntax error at or near "gst"\nLINE 1: gst\n        ^\n')
2021-01-08 10:31:30,555 (5368/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "gst"\nLINE 1: gst\n        ^\n\n'
2021-01-08 10:40:29,891 (5368/MainThread) pgcli.pgexecute ERROR - sql: 'select * from "Timerrrr"', error: UndefinedTable('relation "Timerrrr" does not exist\nLINE 1: select * from "Timerrrr"\n                      ^\n')
2021-01-08 10:40:29,892 (5368/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "Timerrrr" does not exist\nLINE 1: select * from "Timerrrr"\n                      ^\n\n'
2021-01-11 19:38:50,782 (3378/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-11 19:38:50,782 (3378/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-11 19:39:00,006 (3444/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-11 19:39:00,006 (3444/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-09 17:51:06,834 (97923/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-09 17:51:06,835 (97923/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-09 17:51:08,646 (97923/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 54545?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 54545?\n\n'
2021-04-09 17:51:19,760 (97930/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-09 17:51:19,761 (97930/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-09 17:51:25,142 (97930/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "root"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "root"\n\n'
2021-04-09 17:51:28,613 (97945/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-09 17:51:28,614 (97945/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-09 17:51:34,428 (97945/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "root"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "root"\n\n'
2021-04-09 18:04:01,494 (98339/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-09 18:04:01,495 (98339/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-09 18:04:52,126 (98339/MainThread) pgcli.pgexecute ERROR - sql: '\\!ls', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\!ls\n        ^\n')
2021-04-09 18:04:52,127 (98339/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\!ls\n        ^\n\n'
2021-04-09 18:05:08,450 (98339/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2021-04-09 18:05:08,451 (98339/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2021-04-09 18:09:23,473 (98339/MainThread) pgcli.pgexecute ERROR - sql: 'create table urls (', error: SyntaxError('syntax error at end of input\nLINE 1: create table urls (\n                           ^\n')
2021-04-09 18:09:23,473 (98339/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: create table urls (\n                           ^\n\n'
2021-04-09 18:12:31,716 (98339/MainThread) pgcli.pgexecute ERROR - sql: "insert into urls values ('/foo', 'https://www.reddit.com'), ('/bar', 'https://go.com')", error: InvalidTextRepresentation('invalid input syntax for type integer: "/foo"\nLINE 1: insert into urls values (\'/foo\', \'https://www.reddit.com\'), ...\n                                 ^\n')
2021-04-09 18:12:31,716 (98339/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "/foo"\nLINE 1: insert into urls values (\'/foo\', \'https://www.reddit.com\'), ...\n                                 ^\n\n'
2021-06-16 17:57:14,400 (52037/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-06-16 17:57:14,404 (52037/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-06-16 17:57:33,041 (52037/MainThread) pgcli.pgexecute ERROR - sql: '\\', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\\n        ^\n')
2021-06-16 17:57:33,043 (52037/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\\n        ^\n\n'
2021-06-16 17:57:36,967 (52037/MainThread) pgcli.pgexecute ERROR - sql: 'i', error: SyntaxError('syntax error at or near "i"\nLINE 1: i\n        ^\n')
2021-06-16 17:57:36,968 (52037/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "i"\nLINE 1: i\n        ^\n\n'
2021-06-16 18:01:04,613 (52888/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-06-16 18:01:04,613 (52888/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-06-16 18:04:04,321 (52888/MainThread) pgcli.pgexecute ERROR - sql: 'ls', error: SyntaxError('syntax error at or near "ls"\nLINE 1: ls\n        ^\n')
2021-06-16 18:04:04,324 (52888/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "ls"\nLINE 1: ls\n        ^\n\n'
2021-07-12 11:12:50,711 (28123/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-12 11:12:50,712 (28123/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-12 11:13:33,604 (28123/MainThread) pgcli.pgexecute ERROR - sql: 'eixt', error: SyntaxError('syntax error at or near "eixt"\nLINE 1: eixt\n        ^\n')
2021-07-12 11:13:33,605 (28123/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "eixt"\nLINE 1: eixt\n        ^\n\n'
2021-07-12 11:15:44,354 (28505/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-12 11:15:44,354 (28505/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-12 11:19:14,692 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'create table snippets (', error: SyntaxError('syntax error at end of input\nLINE 1: create table snippets (\n                               ^\n')
2021-07-12 11:19:14,693 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: create table snippets (\n                               ^\n\n'
2021-07-12 11:22:27,457 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'create table snippets (\nid INTEGER not null primary key,\ntitle VARCHAR(100) not null,\ncontent TEXT not null,\ncreated datetime not null,\nexpires datetime not null,\n)', error: SyntaxError('syntax error at or near ")"\nLINE 7: )\n        ^\n')
2021-07-12 11:22:27,457 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 7: )\n        ^\n\n'
2021-07-12 11:22:42,050 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'create table snippets (\nid INTEGER not null primary key,\ntitle VARCHAR(100) not null,\ncontent TEXT not null,\ncreated datetime not null,\nexpires datetime not null\n)', error: UndefinedObject('type "datetime" does not exist\nLINE 5: created datetime not null,\n                ^\n')
2021-07-12 11:22:42,050 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: type "datetime" does not exist\nLINE 5: created datetime not null,\n                ^\n\n'
2021-07-12 11:30:29,269 (28505/MainThread) pgcli.pgexecute ERROR - sql: "insert into snippets (title, content, created, expires) values (\n'An old silent pond',\n'An old silent pond...\\nA frog jumps into the pond,\\nsplash! Silence again.',\ntimezone('utc', NOW()),\ntimezone('utc', NOW() + '365 days')\n)", error: NotNullViolation('null value in column "id" of relation "snippets" violates not-null constraint\nDETAIL:  Failing row contains (null, An old silent pond, An old silent pond...\\nA frog jumps into the pond,\\nsplash! Sile..., 2021-07-12 16:30:29.272689, 2022-07-12 16:30:29.272689).\n')
2021-07-12 11:30:29,269 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.NotNullViolation: null value in column "id" of relation "snippets" violates not-null constraint\nDETAIL:  Failing row contains (null, An old silent pond, An old silent pond...\\nA frog jumps into the pond,\\nsplash! Sile..., 2021-07-12 16:30:29.272689, 2022-07-12 16:30:29.272689).\n\n'
2021-07-12 11:33:05,865 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'delete table snippets', error: SyntaxError('syntax error at or near "table"\nLINE 1: delete table snippets\n               ^\n')
2021-07-12 11:33:05,866 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: delete table snippets\n               ^\n\n'
2021-07-12 11:36:04,560 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'create table snippets (\nid SERIAL,\ntitle VARCHAR(100) not null,\ncontent TEXT not null,\ncreated datetime not null,\nexpires datetime not null\n)', error: UndefinedObject('type "datetime" does not exist\nLINE 5: created datetime not null,\n                ^\n')
2021-07-12 11:36:04,560 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: type "datetime" does not exist\nLINE 5: created datetime not null,\n                ^\n\n'
2021-07-12 11:50:43,337 (28505/MainThread) pgcli.pgexecute ERROR - sql: "create user 'web'@'localhost'", error: SyntaxError('syntax error at or near "\'web\'"\nLINE 1: create user \'web\'@\'localhost\'\n                    ^\n')
2021-07-12 11:50:43,338 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\'web\'"\nLINE 1: create user \'web\'@\'localhost\'\n                    ^\n\n'
2021-07-12 11:53:34,529 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'grant select, insert on snippetbox.* to snippetbox', error: SyntaxError('syntax error at or near "to"\nLINE 1: grant select, insert on snippetbox.* to snippetbox\n                                             ^\n')
2021-07-12 11:53:34,530 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "to"\nLINE 1: grant select, insert on snippetbox.* to snippetbox\n                                             ^\n\n'
2021-07-12 11:54:28,790 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'grant connect on snippetbox to snippetbox', error: UndefinedTable('relation "snippetbox" does not exist\n')
2021-07-12 11:54:28,790 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "snippetbox" does not exist\n\n'
2021-07-12 11:55:17,348 (28505/MainThread) pgcli.pgexecute ERROR - sql: 'grant pg_read_all_data to snippetbox', error: UndefinedObject('role "pg_read_all_data" does not exist\n')
2021-07-12 11:55:17,348 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: role "pg_read_all_data" does not exist\n\n'
2021-07-12 11:55:23,689 (28505/MainThread) pgcli.pgexecute ERROR - sql: '\\v', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\v\n        ^\n')
2021-07-12 11:55:23,690 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\v\n        ^\n\n'
2021-07-12 11:55:26,379 (28505/MainThread) pgcli.pgexecute ERROR - sql: '\\version', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\version\n        ^\n')
2021-07-12 11:55:26,379 (28505/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\version\n        ^\n\n'
2021-07-12 18:19:50,722 (85820/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-12 18:19:50,723 (85820/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-21 18:27:26,884 (26644/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-21 18:27:26,884 (26644/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-22 14:58:09,103 (53387/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-22 14:58:09,104 (53387/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-22 14:58:09,111 (53387/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-07-22 14:58:13,471 (53394/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-22 14:58:13,472 (53394/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-22 14:59:10,916 (53394/MainThread) pgcli.pgexecute ERROR - sql: 'create database react-golang-jwt', error: SyntaxError('syntax error at or near "-"\nLINE 1: create database react-golang-jwt\n                             ^\n')
2021-07-22 14:59:10,917 (53394/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "-"\nLINE 1: create database react-golang-jwt\n                             ^\n\n'
2021-07-22 18:30:50,509 (74782/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-22 18:30:50,510 (74782/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-22 18:31:52,091 (74782/MainThread) pgcli.pgexecute ERROR - sql: 'create table users (\nid SERIAL,\ntitle VARCHAR(100) not null,\n)', error: SyntaxError('syntax error at or near ")"\nLINE 4: )\n        ^\n')
2021-07-22 18:31:52,093 (74782/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near ")"\nLINE 4: )\n        ^\n\n'
2021-07-22 19:09:41,100 (79608/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-22 19:09:41,101 (79608/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 10:00:56,066 (7141/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-23 10:00:56,067 (7141/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 10:00:57,425 (7141/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not connect to server: Connection refused\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 5432?\ncould not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 5432?\n\n'
2021-07-23 10:02:41,261 (7401/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-23 10:02:41,261 (7401/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 10:02:48,230 (7401/MainThread) pgcli.pgexecute ERROR - sql: 'select version', error: UndefinedColumn('column "version" does not exist\nLINE 1: select version\n               ^\n')
2021-07-23 10:02:48,232 (7401/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "version" does not exist\nLINE 1: select version\n               ^\n\n'
2021-07-23 10:06:18,691 (7401/MainThread) pgcli.pgexecute ERROR - sql: 'create table if not exists users (', error: SyntaxError('syntax error at end of input\nLINE 1: create table if not exists users (\n                                          ^\n')
2021-07-23 10:06:18,691 (7401/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: create table if not exists users (\n                                          ^\n\n'
2021-07-23 10:06:32,021 (7401/MainThread) pgcli.pgexecute ERROR - sql: 'create table if not exists users (\nid SERIAL', error: SyntaxError('syntax error at end of input\nLINE 2: id SERIAL\n                 ^\n')
2021-07-23 10:06:32,021 (7401/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 2: id SERIAL\n                 ^\n\n'
2021-07-23 10:06:54,087 (7401/MainThread) pgcli.pgexecute ERROR - sql: 'create table if not exists users (\nid SERIAL,\nuser varchar(100) not null,\n)', error: SyntaxError('syntax error at or near "user"\nLINE 3: user varchar(100) not null,\n        ^\n')
2021-07-23 10:06:54,087 (7401/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "user"\nLINE 3: user varchar(100) not null,\n        ^\n\n'
2021-07-23 10:06:58,563 (7401/MainThread) pgcli.pgexecute ERROR - sql: 'create table if not exists users (\nid SERIAL,\nuser varchar(100) not null\n)', error: SyntaxError('syntax error at or near "user"\nLINE 3: user varchar(100) not null\n        ^\n')
2021-07-23 10:06:58,564 (7401/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "user"\nLINE 3: user varchar(100) not null\n        ^\n\n'
2021-07-23 17:12:32,887 (5288/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-23 17:12:32,888 (5288/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 17:15:53,698 (5480/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-23 17:15:53,698 (5480/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 17:29:12,725 (5935/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-07-23 17:29:12,726 (5935/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-07-23 17:30:26,809 (5935/MainThread) pgcli.pgexecute ERROR - sql: "insert into users (username, password) values ('foo', 'bar')", error: UniqueViolation('duplicate key value violates unique constraint "users_username_key"\nDETAIL:  Key (username)=(foo) already exists.\n')
2021-07-23 17:30:26,810 (5935/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "users_username_key"\nDETAIL:  Key (username)=(foo) already exists.\n\n'
